INSERT INTO dm_group (dss_name, dss_description) VALUES ('cardioreanimation_department', 'Отделение кардиореанимации');
INSERT INTO dm_group (dss_name, dss_description) VALUES ('cardioreanimation_department_head', 'Зав. отделения кардиореанимации');
INSERT INTO dm_group (dss_name, dss_description) VALUES ('xray_department', 'Отделение РХМДиЛ');
INSERT INTO dm_group (dss_name, dss_description) VALUES ('xray_department_head', 'Зав. отделения РХМДиЛ');
INSERT INTO dm_group (dss_name, dss_description) VALUES ('anesthesiology_department', 'Отделение анестезиологии');
INSERT INTO dm_group (dss_name, dss_description) VALUES ('therapy_deputy_head', 'Зам. главного врача по терапии');
INSERT INTO dm_group (dss_name, dss_description) VALUES ('anesthesiology_head', 'Зав. центра анестезиологии и реанимации');
INSERT INTO dm_group (dss_name, dss_description) VALUES ('surgery_head', 'Зав. центра хирургии');
INSERT INTO dm_group (dss_name, dss_description) VALUES ('duty_administrators', 'Дежурные администраторы');
INSERT INTO dm_group (dss_name, dss_description) VALUES ('nurses', 'Дежурные мед. сестры');
INSERT INTO dm_group (dss_name, dss_description) VALUES ('clinical_pharmacologists', 'Клинические фармакологи');